quarkus.http.port=8080

ship.api.url=https://ship-player1.apps.cluster-qx6hh.qx6hh.sandbox3444.opentlc.com

quarkus.rest-client.ship-api.url=${ship.api.url}
quarkus.rest-client.ship-api.scope=jakarta.inject.Singleton
