quarkus.http.port=8080

ship.api.url=https://ship-player2.apps.cluster-5hrgj.5hrgj.sandbox1830.opentlc.com

quarkus.rest-client.ship-api.url=${ship.api.url}
quarkus.rest-client.ship-api.scope=jakarta.inject.Singleton
